# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "David Zuñiga"
description: > # this means to ignore newlines until "email:"
   Data Scientist | Exploring data and building AI models

email: j.d.zuniga@hotmail.com

#home and floating picture
logo: "/assets/images/blog.jpg"
float_logo: false

# home cover
cover: "/assets/images/home_background.jpg"

name: 'David Zuñiga' # copyright
author: 'David Zuñiga'
# author picture
author_image: "/assets/images/profile.jpg"

paginate:	10

social:
  - icon:	github
    url:	https://github.com/jdzuniga
    desc:	github

